function Hd = FIRbandpass(fc1, fc2, fs)
%FIRBANDPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
% Generated on: 14-Jun-2021 01:59:49

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = fs;  % Sampling Frequency

N    = 50;       % Order
Fc1  = fc1;     % First Cutoff Frequency
Fc2  = fc2;    
flag = 'scale';  

win = blackman(N+1);

b  = fir1(N, [Fc1 Fc2]/Fs/2, 'bandpass',win, flag);

Hd = dfilt.dffir(b);
%Hd = b;



% [EOF]
