function Hd = FIRlowpass(fs,fc)
%FIRLOWPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
% Generated on: 14-Jun-2021 01:30:04

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = fs;  % Sampling Frequency

N    = 50;       % Order
Fc   = fc;      % Cutoff Frequency
flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
%win = blackman(N+1);
disp(Fs)
disp(Fc/Fs/2);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/Fs/2, 'low', flag);
Hd = dfilt.dffir(b);
%Hd = b;

% [EOF]
